name: PHP Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Friday
        with:
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          args: --colors --testdox